### ISSUE TITLE
CountSubquery not built when using only boolean criteria

### ISSUE THREAD

**Issue by Edubits** [omnifaces/omnipersistence#20]
A boolean Criteria doesn't need any parameterValues. If this is the only Criteria used this causes
```
pageBuilder.shouldBuildCountSubquery(!parameterValues.isEmpty());
```
not be set to true in `BaseEntityService.buildTypedQuery`. The result is the displayed number of records is the total number instead of the filtered number.

**Comment by BalusC** [comment]
Fixed in https://github.com/omnifaces/omnipersistence/commit/946e02bc4d20097284c34d008f92b41d0b342b34#diff-b95bff2acfb93244986448a03cee7a57R1614
