### ISSUE TITLE
Filtering on wrapped aggregated fields not possible

### ISSUE THREAD

**Issue by Edubits** [omnifaces/omnipersistence#28]
When using a mapping like the following:
```
LinkedHashMap<Getter<YourEntityDTO>, Expression<?>> mapping = new LinkedHashMap<>();
mapping.put(YourEntityDTO::getId, root.get("id"));
mapping.put(YourEntityDTO::isFree, builder.equal(builder.sum(child.get("price"), 0));
```
it's not detected as an aggregation when adding a filter on the `isFree` field. The filter will be rendered as a `WHERE` clause, while it should be `HAVING`.

**Comment by Edubits** [comment]
As a workaround I have overriden `Provider.HIBERNATE.isAggregation` as follows:
```
@Override
public boolean isAggregation(Expression<?> expression) {
	return (HIBERNATE_BASIC_FUNCTION_EXPRESSION.get().isInstance(expression) && (boolean) invokeMethod(expression, "isAggregation"))
			|| (
					findClass("org.hibernate.query.criteria.internal.predicate.ComparisonPredicate").get().isInstance(expression) &&
							(
									isAggregation(invokeMethod(expression, "getLeftHandOperand"))
											|| isAggregation(invokeMethod(expression, "getRightHandOperand"))
							)
	);
}
```
This adds support for (nested) comparisons where either the left or righthandside of the operation is a aggregation.

**Comment by BalusC** [comment]
Fixed, thanks for workaround hint.

Might only need to check this use case as well for EclipseLink and OpenJPA.
