### ISSUE TITLE
The attribute [id] of class [xy] is mapped to a primary key column in the database. Updates are not allowed

### ISSUE THREAD

**Issue by introcodelabs** [omnifaces/omnipersistence#30]
Performing a delete on an entity, fires following exception:

The attribute [id] of class [] is mapped to a primary key column in the database. Updates are not allowed.

public void delete(E entity) {
        if (entity.getClass().isAnnotationPresent(NonDeletable.class)) {
            throw new NonDeletableEntityException(entity);
        } else {
            this.getEntityManager().remove(this.manage(entity));
            entity.setId((Comparable)null);
        }
    }

The exception is thrown at entity.setId((Comparable)null);

**Comment by BalusC** [comment]
This is a bug in EclipseLink. You should actually pass an unmanaged instance into that method.
