### ISSUE TITLE
Add ability to operate on collections

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/omnipersistence#6]
Hi there

It would be nice to have the following methods provided by the BaseEntityService:

```
public List<I> persist(List<E> entities) 
public List<E> update(List<E> entities)
public List<E> save(List<E> entities)
public void reset(List<E> entities)
public void delete(List<E> entities)
```

Are there any arguments against this feature I might miss? 
I usually add them to a CustomBaseEntityService.

**Comment by BalusC** [comment]
For `update` and `delete` it would certainly be useful. I'm not sure about others.

**Comment by arjantijms** [comment]
@BalusC didn't we had those in the DF version of the entity service as well? I remember them being extra useful with an option for batching, such as when using @janbeernink 's [batcher](https://github.com/omnifaces/omniutils/blob/develop/src/main/java/org/omnifaces/utils/stream/ForEachBatchCollector.java).

I think we had something like `delete(List<E> list, int batchSize)` back then.

**Comment by arjantijms** [comment]
As @janbeernink mentioned, supporting `Iterable` instead of `List` also has the advantage of not necessarily having to populate a list eagerly.
